# Temporary mock dataset mirrored from data/companies.csv.

COMPANIES = [
    {
        "company": "NVIDIA Corporation (NVDA)",
        "role": "Compute/Server",
        "moat": 5,
        "margin_pct": 60.4,
        "growth_pct": 45.0,
        "eff_score": 5,
        "primary_risk": "Concentration",
        "status": "Profitable",
        "margin_score": 5,
        "tafgs": 1215,
    },
    {
        "company": "Dell Technologies (DELL)",
        "role": "Compute/Server",
        "moat": 2,
        "margin_pct": 7.2,
        "growth_pct": 20.0,
        "eff_score": 3,
        "primary_risk": "Concentration",
        "status": "Profitable",
        "margin_score": 2,
        "tafgs": 281,
    },
    {
        "company": "Credo Technology Group (CRDO)",
        "role": "Networking",
        "moat": 4,
        "margin_pct": 47.8,
        "growth_pct": 60.0,
        "eff_score": 5,
        "primary_risk": "Concentration",
        "status": "Profitable",
        "margin_score": 5,
        "tafgs": 765,
    },
    {
        "company": "Broadcom (AVGO)",
        "role": "Networking",
        "moat": 5,
        "margin_pct": 64.9,
        "growth_pct": 35.0,
        "eff_score": 5,
        "primary_risk": "Concentration",
        "status": "Profitable",
        "margin_score": 5,
        "tafgs": 1134,
    },
    {
        "company": "Eaton Corporation plc (ETN)",
        "role": "Power Infrastructure",
        "moat": 4,
        "margin_pct": 24.5,
        "growth_pct": 25.0,
        "eff_score": 4,
        "primary_risk": "Cyclicality",
        "status": "Profitable",
        "margin_score": 4,
        "tafgs": 498,
    },
    {
        "company": "GE Vernova Inc. (GEV)",
        "role": "Power Infrastructure",
        "moat": 4,
        "margin_pct": 8.4,
        "growth_pct": 15.0,
        "eff_score": 4,
        "primary_risk": "Execution",
        "status": "Profitable",
        "margin_score": 3,
        "tafgs": 246,
    },
    {
        "company": "Vertiv Holdings (VRT)",
        "role": "Cooling Systems",
        "moat": 4,
        "margin_pct": 20.4,
        "growth_pct": 20.0,
        "eff_score": 4,
        "primary_risk": "Supply Chain",
        "status": "Profitable",
        "margin_score": 3,
        "tafgs": 410,
    },
    {
        "company": "Modine Manufacturing (MOD)",
        "role": "Cooling Systems",
        "moat": 3,
        "margin_pct": 17.2,
        "growth_pct": 22.0,
        "eff_score": 3,
        "primary_risk": "Cyclicality",
        "status": "Profitable",
        "margin_score": 3,
        "tafgs": 329,
    },
    {
        "company": "Jacobs Solutions Inc. (J)",
        "role": "Engineering & Construction",
        "moat": 3,
        "margin_pct": 7.3,
        "growth_pct": 20.0,
        "eff_score": 3,
        "primary_risk": "Execution",
        "status": "Profitable",
        "margin_score": 2,
        "tafgs": 219,
    },
    {
        "company": "AECOM (ACM)",
        "role": "Engineering & Construction",
        "moat": 3,
        "margin_pct": 7.4,
        "growth_pct": 15.0,
        "eff_score": 3,
        "primary_risk": "Cyclicality",
        "status": "Profitable",
        "margin_score": 2,
        "tafgs": 189,
    },
]


ROLE_OPTIONS = [
    "Compute/Server",
    "Networking",
    "Power Infrastructure",
    "Cooling Systems",
    "Engineering & Construction",
]
