# Sample data lang

COMPANIES = [
    {
        "company": "Nvidia",
        "role": "Compute/GPU",
        "moat": 5,
        "margin_pct": 55.0,
        "growth_pct": 45.0,
        "eff_score": 5,
        "primary_risk": "Concentration",
        "status": "Profitable",
        "margin_score": 5,
        "tafgs": 1215,
    },
    {
        "company": "Arista",
        "role": "Networking",
        "moat": 4,
        "margin_pct": 38.0,
        "growth_pct": 30.0,
        "eff_score": 4,
        "primary_risk": "Competition",
        "status": "Profitable",
        "margin_score": 4,
        "tafgs": 841,
    },
    {
        "company": "Vertiv",
        "role": "CRAHS/Power",
        "moat": 4,
        "margin_pct": 25.0,
        "growth_pct": 25.0,
        "eff_score": 5,
        "primary_risk": "Supply Chain",
        "status": "Profitable",
        "margin_score": 5,
        "tafgs": 324,
    },
    {
        "company": "Eaton",
        "role": "UPS/Switchgear",
        "moat": 4,
        "margin_pct": 18.0,
        "growth_pct": 15.0,
        "eff_score": 3,
        "primary_risk": "Cyclicality",
        "status": "Profitable",
        "margin_score": 2,
        "tafgs": 121,
    },
    {
        "company": "Schneider",
        "role": "PDU/UPS",
        "moat": 4,
        "margin_pct": 20.0,
        "growth_pct": 18.0,
        "eff_score": 4,
        "primary_risk": "Execution",
        "status": "Profitable",
        "margin_score": 3,
        "tafgs": 226,
    },
    {
        "company": "Speculative AI",
        "role": "Software",
        "moat": 2,
        "margin_pct": -5.0,
        "growth_pct": 60.0,
        "eff_score": 2,
        "primary_risk": "Liquidity",
        "status": "Unprofitable",
        "margin_score": 1,
        "tafgs": 117,
    },
]


ROLE_OPTIONS = [
    "Compute/GPU",
    "Networking",
    "CRAHS/Power",
    "UPS/Switchgear",
    "PDU/UPS",
    "Software",
]
